image: registry:5000/ircbot-ubuntu:v0.2.0

stages:
  - Source
  - Build
  - Test
  - Package

variables:
  GIT_SUBMODULE_STRATEGY: recursive

source:
  stage: Source
  tags:
    - s3
  script:
    - tar czf ircbot-source.tar.gz cmake CMakeLists.txt config gtest include packaging plugins program *.md source tests
  artifacts:
    paths:
      - ircbot-source.tar.gz

build:
  stage: Build
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug ..
    - make -j $(nproc)
    - mkdir install_root
    - make DESTDIR=./install_root install
    - tar cJf ../ubuntu1604-ircbot-binary.tar.xz ./install_root/*
    - cd ..
    - tar cJf ubuntu1604-build.tar.xz ./build
  artifacts:
    paths:
      - ubuntu1604-ircbot-binary.tar.xz
      - ubuntu1604-build.tar.xz

test:
  stage: Test
  tags:
    - s3
  script:
    - tar xf ubuntu1604-build.tar.xz
    - ls -la .
    - ls -la build
    - cd build
    - ctest

deb:
  stage: Package
  tags:
    - s3
  script:
    - cp ircbot-source.tar.gz packaging/deb/ircbot_0.2.0.orig.tar.gz
    - cd packaging/deb
    - mkdir ircbot-0.2.0
    - cd ircbot-0.2.0
    - tar xf ../ircbot_0.2.0.orig.tar.gz
    - cp -r ../debian .
    - debuild -uc -us
  artifacts:
    paths:
      - "packaging/deb/*.dsc"
      - "packaging/deb/*.debian.tar.xz"
      - "packaging/deb/*.orig.tar.gz"
      - "packaging/deb/*.deb"

rpm:
  image: registry:5000/ircbot-fedora:dev
  stage: Package
  tags:
    - s3
  script:
    - cd packaging/rpm
    - rpmbuild -ba ircbot.spec
