image: kolk/ircbot:26022018

stages:
  - Source
  - Build
  - Test
  - Package
  - Deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

source:
  stage: Source
  tags:
    - s3
  script:
    - tar czf ircbot-source.tar.gz cmake CMakeLists.txt config gtest include packaging plugins program *.md source tests docs
  artifacts:
    paths:
      - ircbot-source.tar.gz

build:
  stage: Build
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug ..
    - make -j $(nproc)
    - mkdir install_root
    - make DESTDIR=./install_root install
    - tar cJf ../ubuntu1604-ircbot-binary.tar.xz ./install_root/*
    - cd ..
    - tar cJf ubuntu1604-build.tar.xz ./build
    - cp build/version-info .
  artifacts:
    paths:
      - ubuntu1604-ircbot-binary.tar.xz
      - ubuntu1604-build.tar.xz
      - version-info

docs:
  stage: Build
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make docs
    - tar cJf ../docs.tar.xz docs
  artifacts:
    paths:
      - docs.tar.xz

test:
  stage: Test
  tags:
    - s3
  script:
    - tar xf ubuntu1604-build.tar.xz
    - ls -la .
    - ls -la build
    - cd build
    - ctest

deb:
  stage: Package
  tags:
    - s3
  script:
    - export IRCBOT_VERSION=$(cat version-info)
    - echo ${IRCBOT_VERSION}
    - cp ircbot-source.tar.gz packaging/deb/ircbot_${IRCBOT_VERSION}.orig.tar.gz
    - cd packaging/deb
    - mkdir ircbot-${IRCBOT_VERSION}
    - cd ircbot-${IRCBOT_VERSION}
    - tar xf ../ircbot_${IRCBOT_VERSION}.orig.tar.gz
    - cp -r ../debian .
    - debuild -uc -us
    - cd ../../..
    - cp packaging/deb/*.deb .
  artifacts:
    paths:
      - "*.deb"

rpm:
  image: kolk/ircbot-rpm:27022018
  stage: Package
  tags:
    - s3
  script:
    - mkdir -p rpmbuild/BUILD
    - cd rpmbuild/BUILD
    - tar xf ../../ircbot-source.tar.gz
    - cd ../..
    - rpmbuild --define "_topdir $(realpath ./rpmbuild)" -ba packaging/rpm/ircbot.spec
    - cp ./rpmbuild/SRPMS/*.rpm .
    - cp ./rpmbuild/RPMS/**/*.rpm .
  artifacts:
    paths:
      - "*.rpm"

deploy:ubuntu:
  image: ubuntu:16.04
  stage: Deploy
  tags:
    - s3
  script:
    - export IRCBOT_VERSION=$(cat version-info)
    - echo ${IRCBOT_VERSION}
    - apt update
    - apt install -y ./ircbot_${IRCBOT_VERSION}*.deb
    - ircbot -v

deploy:fedora:
  image: fedora:27
  stage: Deploy
  tags:
    - s3
  script:
    - export IRCBOT_VERSION=$(cat version-info)
    - echo ${IRCBOT_VERSION}
    - yum install -y ./ircbot-${IRCBOT_VERSION}*.x86_64.rpm
    - ircbot -v
