image: registry:5000/ircbot-ubuntu:v0.2.0

stages:
  - Build
  - Test
  - Documentation
  - Package

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: Build
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug ..
    - make -j $(nproc)
    - mkdir install_root
    - make DESTDIR=./install_root install
    - tar cJf ../ubuntu1604-ircbot-binary.tar.xz ./install_root/*
    - cd ..
    - tar cJf ubuntu1604-build.tar.xz ./build
  artifacts:
    paths:
      - ubuntu1604-ircbot-binary.tar.xz
      - ubuntu1604-build.tar.xz

test:
  stage: Test
  tags:
    - s3
  script:
    - tar xf ubuntu1604-build.tar.xz
    - ls -la .
    - ls -la build
    - cd build
    - ctest

docs:
  stage: Documentation
  tags:
    - s3
  script:
    - doxygen Doxyfile
    - tar cJf docs.tar.xz docs
  artifacts:
    paths:
      - docs.tar.xz
