build:ubuntu-16.04:
  image: ubuntu:16.04
  tags:
    - x86
  script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y build-essential cmake libboost-all-dev
    - mkdir build
    - cd build
    - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug ..
    - make

build:debian-9:
  image: debian:9
  tags:
    - x86
  script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y build-essential cmake libboost-all-dev
    - mkdir build
    - cd build
    - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug ..
    - make
