build:ubuntu-16.04:
  image: registry:5000/ircbot-ubuntu:dev
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug ..
    - make

build:debian-9:
  image: registry:5000/ircbot-debian:dev
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug ..
    - make

build:fedora:
  image: registry:5000/ircbot-fedora:dev
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake3 -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug .. 
    - make
