stages:
  - Build
  - Package

build:ubuntu-16.04:
  image: registry:5000/ircbot-ubuntu:dev
  stage: Build
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug ..
    - make -j $(nproc)
    - mkdir install_root
    - make DESTDIR=./install_root install
    - tar cJf ../ubuntu1604-ircbot-binary.tar.xz ./install_root/*
    - tar cJf ../ubuntu1604-build.tar.xz ../build
  artifacts:
    paths:
      - ubuntu1604-ircbot-binary.tar.xz

test:ubuntu-16.04:
    image: registry:5000/ircbot-ubuntu:dev
    stage: Test
    tags:
      - s3
    script:
      - tar xf ubuntu1604-build.tar.xz
      - ls -la .
      - ls -la build

build:debian-9:
  image: registry:5000/ircbot-debian:dev
  stage: Build
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug ..
    - make -j $(nproc)
    - mkdir install_root
    - make DESTDIR=./install_root install
    - tar cJf ../deb9-ircbot-binary.tar.xz ./install_root/*
    - tar cJf ../deb9-build.tar.xz ../build
  artifacts:
    paths:
      - deb9-ircbot-binary.tar.xz

build:fedora:
  image: registry:5000/ircbot-fedora:dev
  stage: Build
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake3 -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug .. 
    - make -j $(nproc)
    - mkdir install_root
    - make DESTDIR=./install_root install
    - tar cJf ../fedora-ircbot-binary.tar.xz ./install_root/*
    - tar cJf ../fedora-build.tar.xz ../build
  artifacts:
    paths:
      - fedora-ircbot-binary.tar.xz
