stages:
  - Build
  - Package

build:ubuntu-16.04:
  image: registry:5000/ircbot-ubuntu:dev
  stage: Build
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug ..
    - make -j $(nproc)
    - mkdir install_root
    - make DESTDIR=./install_root install
    - tar cJf ../ubuntu1604-ircbot-binary.tar.xz ./install_root/*
  artifacts:
    paths:
      - ubuntu1604-ircbot-binary.tar.xz

build:debian-9:
  image: registry:5000/ircbot-debian:dev
  stage: Build
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug ..
    - make -j $(nproc)
    - mkdir install_root
    - make DESTDIR=./install_root install
    - tar cJf ../deb9-ircbot-binary.tar.xz ./install_root/*
    - cd ..
  artifacts:
    paths:
      - deb9-ircbot-binary.tar.xz

build:fedora:
  image: registry:5000/ircbot-fedora:dev
  stage: Build
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake3 -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug .. 
    - make -j $(nproc)
    - mkdir install_root
    - make DESTDIR=./install_root install
    - tar cJf ../fedora-ircbot-binary.tar.xz ./install_root/*
  artifacts:
    paths:
      - fedora-ircbot-binary.tar.xz
