build:ubuntu-16.04:
  image: registry:5000/ircbot-ubuntu:dev
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug ..
    - make

build:debian-9:
  image: registry:5000/ircbot-debian:dev
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug ..
    - make

build:centos7:
  image: registry:5000/ircbot-centos7:dev
  tags:
    - s3
  script:
    - mkdir build
    - cd build
    - echo "cmake3 -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug .. && make" | scl enable devtoolset-7 bash -
