server: kolk.cc
port: 6667
plugin_token: __secret__
admin_port:
  path: "/tmp/ircbot.sock"
log:
- level: INFO
  file: "-stdout"
plugins:
  so://./plugins/init/init.so:
    nick: LoIRCBot
    user: LoIRCBot
    alternative_nicks:
    - IRCBot_1
    - IRCBot_2
    real_name: IRCBot
    invisible: false
    wallops: false
  so://./plugins/ping/ping.so: {}
  so://./plugins/uptime/uptime.so: {}
  so://./plugins/join/join.so:
    channels:
    - "#IRCBot"
