FROM fedora:27
MAINTAINER Kacper Kołodziej <kacper@kolodziej.it>

RUN yum update -y && \
    yum install -y xz boost-devel cmake3 gcc-c++ make rpmdevtools \
                   protobuf-devel protobuf-compiler \
                   python-devel python3-devel
